service: serverlesswebapp

provider:
    name: aws
    runtime: nodejs6.10
    stage: dev
    region: us-east-1

package:
    include: src/server/**

functions:
    default:
        handler: src/server/default.handler
        events:
            - http: ANY /
            - http: "ANY {proxy+}"
    getGames:
        handler: src/server/getGames.handler
        events:
            - http: GET /games

custom:
    webpack:
        webpackConfig: ./webpack.server.config.js

plugins:
    - serverless-webpack
    - serverless-offline
