service: serverlesswebapp

provider:
    name: aws
    runtime: nodejs6.10
    stage: dev
    region: us-east-1

package:
    include: src/server/**

functions:
    test:
        handler: src/server/test.handler
        events:
            - http: ANY /
            - http: "ANY {proxy+}"
