{
    "version": 2,
    "jobs":
        {
            "build":
                {
                    "branches": { "only": ["master"] },
                    "docker": [{ "image": "circleci/node:7.10" }],
                    "steps":
                        [
                            "checkout",
                            { "restore_cache": { "keys": ['v1-dependencies-{{ checksum "package.json" }}', "v1-dependencies-"] } },
                            { "run": { "name": "Install dependencies", "command": "npm install" } },
                            { "save_cache": { "paths": ["node_modules"], "key": 'v1-dependencies-{{ checksum "package.json" }}' } },
                            { "run": { "name": "Configure credentials", "command": "npm run deploy:configure" } },
                            { "run": { "name": "Deploy client", "command": "npm run deploy:client" } },
                            { "run": { "name": "Deploy server", "command": "npm run deploy:server" } },
                        ],
                },
        },
}
